fail_fast: false
exclude: (^external/|^bazel-.*|^bin|^build|compile_commands\.json)
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-merge-conflict
    - id: check-json
      exclude: ".vscode/"
    - id: check-added-large-files
      args: ["--maxkb=1024"]
    - id: requirements-txt-fixer
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.15.12
    hooks:
    # Run the linter.
    - id: ruff-check
      args: [--fix]
    # Run the formatter.
    - id: ruff-format
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.2
    hooks:
    - id: codespell
      args: [-I=.github/WORDS_BAG.txt, -w]
      exclude: ((\.claude/.*)|(.*\.bzl\.tpl)|(.*json.hpp|.*json_fwd.hpp)|(vila/hook/detours/.*))
  - repo: https://github.com/cmake-lint/cmake-lint
    rev: 1.4.3
    hooks:
    - id: cmakelint
