"""
Copyright (C) 2023-2026 The VILA Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

load("@local_config_wdk//:wpp.bzl", "var_providing_rule")
load("@vila//vila/bazel/vila:vila.bzl", "vila_cc_library")

var_providing_rule(name = "set_wpp_vars")

genrule(
    name = "logger_tmh",
    # when generating tmh, the file suffix has to be .cpp
    srcs = [":logger.cpp"],
    outs = [":logger.tmh"],
    cmd_bat = """
    ""$(TRACEWPP)" -dll -I"$(WPPCONFIG)" -ctl:$(GUID) -odir:"$(@D)" $<"
""",
    target_compatible_with = [
        "@platforms//cpu:x86_64",
        "@platforms//os:windows",
    ],
    toolchains = [":set_wpp_vars"],
    visibility = ["//visibility:private"],
)

vila_cc_library(
    name = "logger",
    srcs = [":logger.cpp"],
    hdrs = [":logger.h"],
    defines = select({
        "@vila//vila:use_log": {"VILA_USE_LOG": "1"},
        "//conditions:default": {},
    }),
    local_defines = select({
        "@vila//vila:use_wpp": {"ENABLE_WPP": "1"},
        "//conditions:default": {},
    }),
    textual_hdrs = select({
        "@vila//vila:use_wpp": [":logger_tmh"],
        "//conditions:default": [],
    }),
    visibility = ["//visibility:public"],
    deps = [
        "@fmt",
        "@spdlog",
        "@vila//clim:os",
        "@vila//clim:path",
        "@vila//clim:reflection",
    ],
)

vila_cc_library(
    name = "code_location",
    srcs = [":code_location.cc"],
    hdrs = [":code_location.h"],
    local_defines = select({
        "@vila//vila:use_backtrace": {"VILA_USE_BACKTRACE": "1"},
        "//conditions:default": {},
    }),
    visibility = ["//visibility:public"],
    deps = ["@fmt"],
)
