"""
Copyright (c) 2026 Wenyi Tang
Author: Wenyi Tang
E-mail: wenyitang@outlook.com
"""

constraint_setting(
    name = "vila_toolchain",
)

constraint_value(
    name = "sycl",
    constraint_setting = ":vila_toolchain",
    tags = ["compiler"],
    visibility = ["//visibility:public"],
)

constraint_value(
    name = "bullseye",
    constraint_setting = ":vila_toolchain",
    tags = ["compiler"],
    visibility = ["//visibility:public"],
)
