"""
INTEL CONFIDENTIAL

Copyright (C) 2023 Intel Corporation. All Rights Reserved.

The source code contained or described herein and all documents
related to the source code ("Material") are owned by Intel Corporation
or licensors. Title to the Material remains with Intel
Corporation or its licensors. The Material contains trade
secrets and proprietary and confidential information of Intel or its
licensors. The Material is protected by worldwide copyright
and trade secret laws and treaty provisions. No part of the Material may
be used, copied, reproduced, modified, published, uploaded, posted,
transmitted, distributed, or disclosed in any way without Intel's prior
express written permission.

No License under any patent, copyright, trade secret or other intellectual
property right is granted to or conferred upon you by disclosure or
delivery of the Materials, either expressly, by implication, inducement,
estoppel or otherwise. Any license under such intellectual property rights
must be express and approved by Intel in writing.
"""

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "traits",
    hdrs = [":type_traits.h"],
)

cc_library(
    name = "vt",
    hdrs = [
        ":vt/vt.h",
        ":vt/vt_nn.h",
    ],
    deps = [":traits"],
)

cc_library(
    name = "hash",
    srcs = [
        ":hasher/city_internal.h",
        ":hasher/murmur3_internal.h",
    ],
    hdrs = [
        ":hasher/city.h",
        ":hasher/hash.h",
        ":hasher/murmur3.h",
    ],
)

cc_library(
    name = "os",
    hdrs = [
        ":aligned_malloc.h",
        ":barrier.h",
        ":linux_memcpy_s.h",
        ":os.h",
    ],
)

cc_library(
    name = "path",
    hdrs = [
        ":os_path.h",
        ":path.h",
    ],
    defines = select({
        "@platforms//os:windows": [],
        "//conditions:default": ["HAS_STD_FS"],
    }),
)

cc_library(
    name = "string",
    hdrs = [
        ":const_string.h",
        ":str_replace.h",
        ":str_split.h",
        ":strip.h",
    ],
)

cc_library(
    name = "reflection",
    hdrs = [
        ":reflect.h",
    ],
    deps = [":string"],
)

cc_library(
    name = "container",
    hdrs = [
        ":array_arithmetic.h",
        ":bbox_trait.h",
        ":bounding_box.h",
        ":rect.h",
        ":ringbuffer.h",
        ":stringview_hash_map.h",
    ],
)

cc_library(
    name = "filter",
    hdrs = [
        ":alpha_beta_filter.h",
        ":kalman_filter.h",
    ],
    deps = [
        ":container",
    ],
)

cc_library(
    name = "base64",
    hdrs = [
        ":base64.h",
    ],
)

cc_library(
    name = "math",
    hdrs = [
        ":numerical.h",
        ":quat.h",
    ],
    deps = [":traits"],
)

cc_library(
    name = "argparse",
    hdrs = [":argparse.h"],
    deps = [":string"],
)

cc_library(
    name = "clim",
    deps = [
        ":argparse",
        ":base64",
        ":container",
        ":filter",
        ":hash",
        ":math",
        ":os",
        ":path",
        ":reflection",
        ":string",
        ":vt",
    ],
)
