"""
Copyright (c) 2022 Intel Corporation
Author: Wenyi Tang
E-mail: wenyi.tang@intel.com

"""

CXX_STD = select({
    "@platforms//os:windows": ["-std:c++17"],
    "//conditions:default": ["-std=c++17"],
})

cc_test(
    name = "hash_benchmark",
    testonly = 1,
    srcs = [":hash_benchmark.cpp"],
    copts = CXX_STD,
    tags = ["benchmark"],
    visibility = ["//visibility:private"],
    deps = [
        "//clim:hash",
        "//clim:os",
        "@com_google_benchmark//:benchmark_main",
    ],
)

cc_test(
    name = "string_split_benchmark",
    testonly = 1,
    srcs = [":string_split_benchmark.cpp"],
    copts = CXX_STD,
    tags = ["benchmark"],
    visibility = ["//visibility:private"],
    deps = [
        "//clim:string",
        "@com_google_benchmark//:benchmark_main",
    ],
)

cc_test(
    name = "stringview_hashmap_benchmark",
    testonly = 1,
    srcs = [":stringview_hashmap_benchmark.cpp"],
    copts = CXX_STD,
    tags = ["benchmark"],
    visibility = ["//visibility:private"],
    deps = [
        "//clim:container",
        "//clim:hash",
        "//clim:os",
        "@com_google_benchmark//:benchmark_main",
    ],
)

cc_test(
    name = "ringbuffer_benchmark",
    testonly = 1,
    srcs = [":ringbuffer_benchmark.cpp"],
    copts = CXX_STD,
    tags = ["benchmark"],
    visibility = ["//visibility:private"],
    deps = [
        "//clim:container",
        "@com_google_benchmark//:benchmark_main",
    ],
)

cc_test(
    name = "container_benchmark",
    srcs = ["container_benchmark.cpp"],
    copts = CXX_STD,
    tags = ["benchmark"],
    deps = [
        "@com_google_benchmark//:benchmark_main",
        "@fmt",
    ],
)

cc_test(
    name = "vt_speed_benchmark",
    srcs = ["vt_speed_benchmark.cpp"],
    copts = CXX_STD,
    tags = ["benchmark"],
    deps = [
        "//clim:vt",
        "@com_google_benchmark//:benchmark_main",
    ],
)

cc_test(
    name = "pimpl_benchmark",
    srcs = ["pimpl_benchmark.cpp"],
    copts = CXX_STD,
    tags = ["benchmark"],
    deps = [
        "@com_google_benchmark//:benchmark_main",
    ],
)

cc_test(
    name = "copy_benchmark",
    srcs = ["copy_benchmark.cpp"],
    copts = CXX_STD,
    tags = ["benchmark"],
    deps = [
        "@com_google_benchmark//:benchmark_main",
    ],
)

# cc_test(
#     name = "hashmap_benchmark",
#     srcs = ["hashmap_benchmark.cpp"],
#     copts = CXX_STD,
#     tags = ["benchmark"],
#     deps = [
#         "@abseil-cpp//absl/container:flat_hash_map",
#         "@abseil-cpp//absl/container:node_hash_map",
#         "@com_google_benchmark//:benchmark_main",
#     ],
# )
